### PR TITLE
Create test framework

### PR DESCRIPTION
**Pull request by brainelectronics**
### Added
- Perform MicroPython based unittests on every `Test` workflow run
- Add usage description of docker based MicroPython unittest framework in [USAGE](USAGE.md)
- Add [docker compose file](docker-compose.yaml) based in MicroPython 1.18 image
- Add [TCP client Dockerfile](Dockerfile.client), [TCP host Dockerfile](Dockerfile.host), [unittest Dockerfile](Dockerfile.tests) and [TCP unittest specific Dockerfile](Dockerfile.test_tcp_example). All based on MicroPython 1.18 image
- Add initial test, testing the unittest itself
- Add [unittest](mpy_unittest.py) implementation based on pfalcon's [micropython-unittest](https://github.com/pfalcon/pycopy-lib/blob/56ebf2110f3caa63a3785d439ce49b11e13c75c0/unittest/unittest.py)
- Docstrings available for all functions of [functions.py](umodbus/functions.py), see #27
- Typing hints available for all functions of [functions.py](umodbus/functions.py), [serial.py](umodbus/serial.py) and [tcp.py](umodbus/tcp.py), see #27
- Unittest for [functions.py](umodbus/functions.py), see #16
- Unittest for [const.py](umodbus/const.py), see #16
- [.readthedocs.yaml](.readthedocs.yaml) for Read The Docs, contributes to #26

### Changed
- Use default values for all registers defined in the [example JSON](registers/example.json)
- [TCP host example](examples/tcp_host_example.py) and [TCP client example](examples/tcp_client_example.py) define a static IP address and skip further WiFi setup steps in case a Docker usage is detected by a failing import of the `network` module, contributes to #16
- Define all Modbus function codes as `const()` to avoid external modifications, contributes to #18
- Remove dependency to `Serial` and `requests` from `umodbus.modbus`, see #18
- `ModbusRTU` class is part of [serial.py](umodbus/serial.py), see #18
- `ModbusTCP` class is part of [tcp.py](umodbus/tcp.py), see #18
- `ModbusRTU` and `ModbusTCP` classes and related functions removed from [modbus.py](umodbus/modbus.py), see #18
- Imports changed from:
    - `from umodbus.modbus import ModbusRTU` to `from umodbus.serial import ModbusRTU`
    - `from umodbus.modbus import ModbusTCP` to `from umodbus.tcp import ModbusTCP`
- `read_coils` and `read_discrete_inputs` return a list with the same length as the requested quantity instead of always 8, see #12 and #25
- Common functions `bytes_to_bool` and `to_short` moved to [functions.py](umodbus/functions.py)
- Use HTTPS URL instead of SSH for submodule
- Cleanup of root [README](README.md), content moved to [SETUP](docs/SETUP.md) and [USAGE](docs/USAGE.md), contributes to #30
- Moved [SETUP](docs/SETUP.md) and [USAGE](docs/USAGE.md) into [docs](docs) folder, see #26 contributes to #30
- Use `False` or `0` as default values for registers without a specific initial value in [modbus.py](umodbus/modbus.py)

### Fixed
- `read_coils` returns list with amount of requested coils, see #12
- `read_holding_registers` returns list with amount of requested registers, see #25

### CODE REVIEW

**Review by brainelectronics — COMMENTED** [review]
LGTM

**Review by brainelectronics — COMMENTED** [review]
@beyonlo you can now review [2.0.0-rc8.dev33](https://github.com/brainelectronics/micropython-modbus/releases/tag/2.0.0-rc8.dev33)

**Comment by brainelectronics** [comment]
Keep register mapping in sync between TCP client and tests by using `volumes`. Sync example JSON to test. Import JSON if Docker is used at client

**Comment by beyonlo** [comment]
Thank you very much for this release @brainelectronics

>**Fixed**
>write_multiple_coils function works as specified. Constructed outputs value was incorrect, see https://github.com/brainelectronics/micropython-modbus/issues/22


I tested micropython-modbus `2.0.0rc8.dev33` but that Bug still exists:


**ModBus RTU Slave:**
For the `Slave` I used this [tcp_client_example.py](https://github.com/brainelectronics/micropython-modbus/blob/feature/create-test-framework/examples/tcp_client_example.py)
`register_definitions = {"COILS": {"EXAMPLE_COIL": {"register": 123, "len": 1,  "val": 1  }...
`
```
$ mpremote run tcp_client_example.py
Waiting for WiFi connection...
Connected to WiFi.
('192.168.1.4', '255.255.255.0', '192.168.1.1', '192.168.1.1')
Setting up registers ...
Register setup done
Serving as TCP client on 192.168.1.4:502

```

**ModBus RTU Master results:**

```
>>> from umodbus.tcp import TCP as ModbusTCPMaster
>>> host = ModbusTCPMaster(slave_ip='192.168.1.4', slave_port=502, timeout=5)
>>> host.read_coils(slave_addr=10, starting_addr=123, coil_qty=1)
[True, False, False, False, False, False, False, False]
>>> host.write_multiple_coils(slave_addr=10, starting_address=123, output_values=[1,1,1,0,0,1,1,1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/umodbus/tcp.py", line 522, in write_multiple_coils
  File "/lib/umodbus/tcp.py", line 319, in _send_receive
  File "/lib/umodbus/tcp.py", line 286, in _validate_resp_hdr
ValueError: slave returned exception code: 143
>>> 
```


As I do not know what is the correct usage on the `register_definitions` (commented by #26 and [here](https://github.com/brainelectronics/micropython-modbus/issues/15#issuecomment-1312258037) ), I tested the `Slave` with differents `register_definitions`, because maybe can be just something that I'm doing wrong on the `register_definitions`.

**Try 1:**  (changed **"val"**)
`register_definitions = {"COILS": {"EXAMPLE_COIL": {"register": 123, "len": 1,  "val": [1,0,1,1,1,0,0,1]}...
`

**ModBus RTU Master results:**
```
>>> host.read_coils(slave_addr=10, starting_addr=123, coil_qty=1)
[True, False, False, True, True, True, False, True]
>>> host.write_multiple_coils(slave_addr=10, starting_address=123, output_values=[1,1,1,0,0,1,1,1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/umodbus/tcp.py", line 522, in write_multiple_coils
  File "/lib/umodbus/tcp.py", line 319, in _send_receive
  File "/lib/umodbus/tcp.py", line 286, in _validate_resp_hdr
ValueError: slave returned exception code: 143
>>> 
```


**Try 2:**  (changed **"len"** and **"val"**)
`register_definitions = {"COILS": {"EXAMPLE_COIL": {"register": 123, "len": 8,  "val": [1,0,1,1,1,0,0,1]}...
`

**ModBus RTU Master results:**
Same error of **Try 1**




**Scenario used (`MicroPython 1.19.1` in both):**
ESP32-S3_01 (`Slave`) -------- TCP ------------- ESP32-S3_02 (`Master`)

**Installation was done via pip in both:**
```
>> import upip
>>> upip.index_urls = ['https://test.pypi.org/pypi']
>>> upip.install('micropython-modbus')
Installing to: /lib/
Warning: test.pypi.org SSL certificate is not validated
Installing micropython-modbus 2.0.0rc8.dev33 from https://test-files.pythonhosted.org/packages/c4/03/a2e66a4648dfe5ec1fec176792153e86387d5c679ded58a2b14d800d6da5/micropython-modbus-2.0.0rc8.dev33.tar.gz
```
**Ps**: to be sure that everything is OK with installation (no old `micropython-modbus` versions), first I erase the flash and install the `MicroPython` again, and after the `micropython-modbus` is installed.

**Comment by brainelectronics** [comment]
> Keep register mapping in sync between TCP client and tests by using `volumes`. Sync example JSON to test. Import JSON if Docker is used at client

see bbaf7ab1cf8f67070a7b37b3edb83b0dbbf22192

**Comment by brainelectronics** [comment]
@beyonlo let's try with [2.0.0-rc9.dev33](https://github.com/brainelectronics/micropython-modbus/releases/tag/2.0.0-rc9.dev33) I have to admit that #22 seems not to be fixed. But about #12 and #25 I'm pretty sure. We will get there!

**Comment by brainelectronics** [comment]
@beyonlo  check https://github.com/brainelectronics/micropython-modbus/blob/da9945fccc785bae81c891f9207fb9e419becf4c/registers/example.json to see an example of reading multiple registers and coils

**Comment by beyonlo** [comment]
Hello @brainelectronics 

> @beyonlo let's try with [2.0.0-rc9.dev33](https://github.com/brainelectronics/micropython-modbus/releases/tag/2.0.0-rc9.dev33)

Thank you for this release.  The tests results are below.

> I have to admit that #22 seems not to be fixed.

No problem, when be fixed, please tell me. Anyway, I tried in this new version as well, and that bug really still not fixed.

>@beyonlo check https://github.com/brainelectronics/micropython-modbus/blob/da9945fccc785bae81c891f9207fb9e419becf4c/registers/example.json to see an example of reading multiple registers and coils

Thank you, now is very clear to me what means that `"len"`.  **Suggestion in COIL:** if **"val": 0** works in the same way as **"val": [0]**, my suggestion is to assume as standard to use always` [ ]`, because when people need more than one bit the` [ ] `will be need anyway! Same for others, like as `holding registers`.

> But about #12 and #25 I'm pretty sure. We will get there!

I'm very happy to test this two bugs fixes - they works very good, but still there some problems.

This was the `register_definitions` used in the tests:
```
register_definitions = {
    "COILS": {
        "RESET_REGISTER_DATA_COIL": {
            "register": 42,
            "len": 1,
            "val": 0
        },
        "EXAMPLE_COIL": {
            "register": 123,
            "len": 16,
            "val": [1,0,0,1,1,0,1,1,1,1,1,1,1,1,0,1]
        },
        "EXAMPLE_COIL_MIXED": {
            "register": 124,
            "len": 3,
            "val": [1,1,1],
            "description": "Example COILS registers with length of 2, Coils (setter+getter) [0, 1]",
            "range": "",
            "unit": ""
        }
    },
    "HREGS": {
        "EXAMPLE_HREG": {
            "register": 93,
            "len": 1,
            "val": 19
        },
        "ANOTHER_EXAMPLE_HREG": {
            "register": 94,
            "len": 9,
            "val": [29, 38, 0, 1600, 2150, 5067, 2564, 8450, 3456],
            "description": "Example HREGS registers with length of 3, Hregs (setter+getter) [0, 65535]",
            "range": "",
            "unit": ""
        }
    },
    "ISTS": {
        "EXAMPLE_ISTS": {
            "register": 67,
            "len": 1,
            "val": 0
        }
    },
    "IREGS": {
        "EXAMPLE_IREG": {
            "register": 10,
            "len": 2,
            "val": 60001
        }
    }
}

```

**COIL - read_coils() `coil_qty` problems:**

**Problem 1:** `coil_qty` sometimes works, sometimes no, sometimes work with multiple of 8 and sometimes do not works with `coil_qty` and not works with multiple of 8 as well. I think that we need a standard.
```
>>> host.read_coils(slave_addr=10, starting_addr=42, coil_qty=1)
[False]  <--- OK - get correct value coil_qty=1
>>> host.read_coils(slave_addr=10, starting_addr=42, coil_qty=4)
[False, False, False, False] <--- OK - get correct value coil_qty=4
>> host.read_coils(slave_addr=10, starting_addr=123, coil_qty=4)
[True, True, False, True, True, False, False, True]  <--- NOT OK - get wrong value coil_qty=4, but is multiple of 8 (has 16 values in that register)
>>> host.read_coils(slave_addr=10, starting_addr=123, coil_qty=10)
[True, True, False, True, True, False, False, True, False, False] <--- OK - get correct value coil_qty=10, but is not multiple of 8 anymore and there is 16 values in that register
>>> host.read_coils(slave_addr=10, starting_addr=124, coil_qty=1)
[True, True, True] <-- NOT OK - get wrong value coil_qty=1, and not get multiple of 8 as well.
```

**Problem 2:** `COILs` wrong values. The values read is different from the `register_definitions` set up.

 Look that second value is `True,` and from bit `9` to bit `16` are all `False,` but in the `register_definitions` is different:
```
>>> host.read_coils(slave_addr=10, starting_addr=123, coil_qty=16)
[True, True, False, True, True, False, False, True, False, False, False, False, False, False, False, False] 
```

**Problem 3:**  `coil_qty` bigger than 16 do not get the bits from the next register.
The `Modbus` works with map of registers, like as `123,` `124,` `125` and so on, where each one has two bytes (16 bits). However the `coil_qty` do not works compatible with `ModBus` spec when a register pass to the next register. 

Look that `register_definitions` has register `123` and `124,` where `123` are set all `16` bits, and the register `124` set just `3` bits. But when I choose to read `18` bits, starting from register `123,` the correct need to read all `16` bits from register `123` and get the next `2` bits from the next register (the `124).` That is not working:
```
>>> host.read_coils(slave_addr=10, starting_addr=123, coil_qty=18)
[True, True, False, True, True, False, False, True, False, False, False, False, False, False, False, False, False, False]
```
That's is one of advantage to use `coil_qty`, because if I have for example `5` `COILs` registers , where each register I have all `16` bits set, I do not need to read `5` times, `1` time for each `COIL` register. I need just one request from the Master to read `80` bits `(5` coil registers x `16` bits = `80).` So the command will be: `host.read_coils(slave_addr=10, starting_addr=123, coil_qty=80)`. That will read `16` bits `COILs` of register `123,` `16` bits of register `124,` until `16` bits of register `127`, total `80` bits.  So, talking about the `register_definitions,` another way, instead to use two keys in the **"COILS"**, is to do what you already does in the` holding register` example, where you set all list of registers, with no limit. So in `COIL` will be as well a list (as already is) but that works with more than `16` bits, setting in this example `80` bits. So in the register definitions will be:
```
        "EXAMPLE_COIL": {
            "register": 123,
            "len": 80,
            "val": [1,0,0,1,1,0,1,1,1,1,1,1,1,1,0,1, <-- register 123
                      1,0,0,1,1,0,1,1,1,1,1,1,1,1,0,1, <-- register 124
                      1,0,0,1,1,0,1,1,1,1,1,1,1,1,0,1, <-- register 125
                      1,0,0,1,1,0,1,1,1,1,1,1,1,1,0,1, <-- register 126
                      1,0,0,1,1,0,1,1,1,1,1,1,1,1,0,1] <-- register 127
        },
```
Now user can read just all `16` bits of register `125` for example doing this:
 `host.read_coils(slave_addr=10, starting_addr=125, coil_qty=16)`

To read all bits of register `124,` `125` and `126,` just need to do this:
 `host.read_coils(slave_addr=10, starting_addr=124, coil_qty=48)`


**HOLDING_REGISTERS - read_holding_registers() `register_qty` problems:**

This showing working very good!! I choose to get `50` registers starting from register `94` - works.
```
>>> host.read_holding_registers(slave_addr=10, starting_addr=94, register_qty=50, signed=False)
(29, 38, 0, 1600, 2150, 5067, 2564, 8450, 3456)
```

**Problem 4:**   `register_qty` to not works:

Now I want to read just one register, that will be the register `94`, the `register_qty=1` do not works. I want just register `94,` and result was registers `94,` `95,` `96,` `97,` `98,` `99,` `100,` `101` and `102.`
```
>>> host.read_holding_registers(slave_addr=10, starting_addr=94, register_qty=1, signed=False)
(29, 38, 0, 1600, 2150, 5067, 2564, 8450, 3456)
```

**Problem 5:**  When try to read a specific register from a list of register, it not works

Now I want to read just the register `98` (that is the number `2150).` If the register `94` is the number `29,` following the list, the number `2150` is the register `98.`  But I have error:

```
>>> host.read_holding_registers(slave_addr=10, starting_addr=98, register_qty=1, signed=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/umodbus/tcp.py", line 384, in read_holding_registers
  File "/lib/umodbus/tcp.py", line 297, in _send_receive
  File "/lib/umodbus/tcp.py", line 264, in _validate_resp_hdr
ValueError: slave returned exception code: 131
>>> 
```

Below a picture from the `MODSCAN` showing that list, where each value in the list is one register. `MODSCAN`  `Address` use `register + 1 ` - I don't know why. So for `MODSCAN` register `95` is the register `94` of `register_definitions` 


Screenshot from 2022-12-03 19-15-42

**Comment by brainelectronics** [comment]
@beyonlo something already working for you :) 
May I introduce: THE DOCS 🎉 https://micropython-modbus--33.org.readthedocs.build/en/33/USAGE.html#register-configuration
I'll take care of the newly reported review remarks tomorrow

**Comment by beyonlo** [comment]
Hello @brainelectronics 

> @beyonlo something already working for you :) May I introduce: THE DOCS tada https://micropython-modbus--33.org.readthedocs.build/en/33/USAGE.html#register-configuration 

Wow, I liked so much! Very well done, congrats! :partying_face: Just a note: there is a broken link in the [Documentation](https://micropython-modbus--33.org.readthedocs.build/en/33/USAGE.html#documentation): "The documentation is automatically generated on every merge to the develop branch and available [here](https://micropython-modbus.readthedocs.io/en/latest/)" The `here` link is broken.

>I'll take care of the newly reported review remarks tomorrow

Excellent. Thank you very much! This lib will be amazing :)

**Review by brainelectronics — COMMENTED** [review]
intermediate review by myself. Looks good, but still unresolved findings available

**Comment by brainelectronics** [comment]
@beyonlo I've created the issues #35, #36 and #37 based on your reports. Might it be okay for you to merge this PR and resolve those issues directly afterwards. The initial intention was to create a test framework 😂  which is now in place together with a published documentation.

**Comment by brainelectronics** [comment]
> Hello @brainelectronics
> 
> > @beyonlo something already working for you :) May I introduce: THE DOCS tada https://micropython-modbus--33.org.readthedocs.build/en/33/USAGE.html#register-configuration
> 
> Wow, I liked so much! Very well done, congrats! 🥳 Just a note: there is a broken link in the [Documentation](https://micropython-modbus--33.org.readthedocs.build/en/33/USAGE.html#documentation): "The documentation is automatically generated on every merge to the develop branch and available [here](https://micropython-modbus.readthedocs.io/en/latest/)" The `here` link is broken.
> 
> > I'll take care of the newly reported review remarks tomorrow
> 
> Excellent. Thank you very much! This lib will be amazing :)

I'm aware of the broken link. The link will be working as soon as this PR is merged and the docs are build from develop branch. The https://micropython-modbus--33.org.readthedocs.build/en/33/USAGE.html#register-configuration is just the PR docs build. It will be published to the URL mentioned in the README

**Comment by beyonlo** [comment]
Hi @brainelectronics

> @beyonlo I've created the issues #35, #36 and #37 based on your reports.

I saw that, thank you!

> Might it be okay for you to merge this PR and resolve those issues directly afterwards. The initial intention was to create a test framework joy which is now in place together with a published documentation.

I agree. No problem, it's ok for me :)

**Pull request merged**
